function [fitresult, gof] = createFit(mmg1, mmg2, tau_h)
%CREATEFIT(MMG1,MMG2,TAU_H)
%  Create a fit.
%
%  Data for 'mmgTorqueFit' fit:
%      X Input : mmg1
%      Y Input : mmg2
%      Z Output: tau_h
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Apr-2019 11:19:20


%% Fit: 'mmgTorqueFit'.
[xData, yData, zData] = prepareSurfaceData( mmg1, mmg2, tau_h );

% Set up fittype and options.
ft = fittype( 'poly22' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% % Plot fit with data.
% figure( 'Name', 'mmgTorqueFit' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'mmgTorqueFit', 'tau_h vs. mmg1, mmg2', 'Location', 'NorthEast' );
% % Label axes
% xlabel mmg1
% ylabel mmg2
% zlabel tau_h
% grid on
% view( -94.7, 3.6 );


